
### 用户登录
POST {{host}}/manage/base/login
Content-Type: application/json

{
  "account": "manage",
  "password": "123456."
}

> {% if (response.status == 200) client.global.set("token", response.body.data.token); %}
> {% if (response.status == 200) client.global.set("refresh_token", response.body.data.refresh_token); %}

### 用户信息
GET {{host}}/manage/base/info
Content-Type: application/json
Authorization: Basic {{token}}

### 刷新 token
POST {{host}}/manage/base/refresh-token
Content-Type: application/json
Authorization: Basic {{token}}

{
  "refresh_token": "{{refresh_token}}"
}

> {% if (response.status == 200) client.global.set("token", response.body.data.token); %}
> {% if (response.status == 200) client.global.set("refresh_token", response.body.data.refresh_token); %}

### 用户日志
GET {{host}}/manage/base/logs
Content-Type: application/json
Authorization: Basic {{token}}

### 退出登录
POST {{host}}/manage/base/logout
Content-Type: application/json
Authorization: Basic {{token}}


### 用户注册
POST {{host}}/manage/base/register
Content-Type: application/json
Authorization: Basic {{token}}

{
  "nickname": "测试用户",
  "account": "test",
  "password": "123456."
}
