//go:build ignore

// 将 html/static 下的 zcss.js / zview.js 静态资源生成为 Go 数据文件。
// 运行: go generate ./html  （或: go run ./html/gen.go）
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"
)

const header = `// Code generated by go generate ./html via html/gen.go; DO NOT EDIT.

//go:build !nostatic
// +build !nostatic

package html

// staticAsset 描述一个由脚本生成的静态资源。
type staticAsset struct {
	Name string
	Data []byte
}

// staticFiles 保存通过脚本从 html/static 目录转换而来的静态资源，
// 服务端无需 embed / 读取磁盘，直接经 znet 输出。
var staticFiles = []staticAsset{
`

type staticAsset struct {
	Name string
	Data []byte
}

func main() {
	sources := []string{"static/zcss.js", "static/zview.js"}

	var b bytes.Buffer
	b.WriteString(header)
	for i, src := range sources {
		data, err := os.ReadFile(src)
		if err != nil {
			fmt.Fprintf(os.Stderr, "读取 %s 失败: %v\n", src, err)
			os.Exit(1)
		}
		base := src[strings.LastIndex(src, "/")+1:]
		b.WriteString("\t{Name: ")
		fmt.Fprintf(&b, "%q", base)
		b.WriteString(", Data: []byte(")
		writeQuoted(&b, data)
		b.WriteString(")},\n")
		_ = i
	}
	b.WriteString("}\n")

	if err := os.WriteFile("static_data.go", b.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "写入 static_data.go 失败: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("已生成 static_data.go（%d 字节，%d 个资源）\n", b.Len(), len(sources))
}

// writeQuoted 将 data 编码为安全的 Go 字符串字面量（仅转义 \\、\" 与换行，内容均为 ASCII）。
func writeQuoted(b *bytes.Buffer, data []byte) {
	b.WriteByte('"')
	for _, c := range data {
		switch c {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
}
